# docker compose up -d --build

services:
  sing-box:
    image: ghcr.io/sagernet/sing-box
    container_name: sing-box
    restart: unless-stopped
    environment:
      - ENABLE_DEPRECATED_SPECIAL_OUTBOUNDS=true
    ports:
      - "127.0.0.1:2080:2080"
    volumes:
      - ./config.json:/etc/sing-box/config.json
    command: -D /var/lib/sing-box -C /etc/sing-box/ run
